import numpy as np
import pandas as pd

# all of this would really be accelerated on the gpu in torch or tensorflow but I'm moreso wanting the reps so we are balling on cpu
# realistically this will also be massively memory inefficient. I'll hold that.

# basically the idea is that, even though numpy does most of this out of the box, I want to at least replicate basic C array level math
# because this is how all tensor math will work in low level structural programs. I want visibility on this. It's necessary to do the job right.


''' create a blank matrix with x rows and y cols, init to 0s, essentially requesting the memory for a blank matrix '''
def mat_create(rows, cols):
    matrix = np.zeros((rows, cols))


''' clear a matrix'''
def mat_clear(mat):
    return 

''' copy a matrix'''
def mat_copy(dst, src):
    return 

''' fill the matrix'''
def mat_fill(mat, x):
    return 

''' add 2 matrices '''
def mat_add(out, a, b):
    return 

''' subtract 2 matrices '''
def mat_sub(out, a, b):
    return 

''' multiply 2 matrices '''
def mat_mul(out, a, b, zero_out, transpose_a, transpose_b ):
    return

''' rectified linear unit activation function, returns the max of input value and 0'''
def mat_relu(mat_out, mat_in):
    return 

''' softmax activiation function '''
def mat_softmax(mat_out, mat_in):
    return 

''' loss function, good for dealing with the probability distributions generated by softmax'''
def mat_cross_entropy(mat_out, expected_distribution, actual_distribution):
    return 

''' returns gradient value of the ReLU'''
def mat_relu_grad(mat_out, mat_in):
    return 

''' add the gradient to the softmax'''
def softmax_add_grad(mat_out, mat_in): 
    return 

def mat_cross_entropy_add_grad(mat_out, expected_distribution, actual_distribution):
    return 

''' scale a matrix in place '''
def mat_scale(mat, scale):
    return 


matrix = np.zeros((2, 5))
print(matrix)